/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verifyEmail'
import { Route as authSignUpRouteImport } from './routes/(auth)/signUp'
import { Route as authSignInRouteImport } from './routes/(auth)/signIn'
import { Route as authConfirmSignInRouteImport } from './routes/(auth)/confirmSignIn'
import { Route as authConfirmRegisterRouteImport } from './routes/(auth)/confirmRegister'
import { Route as appLayoutRouteRouteImport } from './routes/(app)/_layout/route'
import { Route as appLayoutZoneRouteImport } from './routes/(app)/_layout/zone'
import { Route as appLayoutProfileRouteImport } from './routes/(app)/_layout/profile'
import { Route as appLayoutPredictionsRouteImport } from './routes/(app)/_layout/predictions'
import { Route as appLayoutNotificationsRouteImport } from './routes/(app)/_layout/notifications'
import { Route as appLayoutDashboardRouteImport } from './routes/(app)/_layout/dashboard'
import { Route as appLayoutCarteRouteImport } from './routes/(app)/_layout/carte'
import { Route as appLayoutAlertsRouteImport } from './routes/(app)/_layout/alerts'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verifyEmail',
  path: '/verifyEmail',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/signUp',
  path: '/signUp',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/signIn',
  path: '/signIn',
  getParentRoute: () => rootRouteImport,
} as any)
const authConfirmSignInRoute = authConfirmSignInRouteImport.update({
  id: '/(auth)/confirmSignIn',
  path: '/confirmSignIn',
  getParentRoute: () => rootRouteImport,
} as any)
const authConfirmRegisterRoute = authConfirmRegisterRouteImport.update({
  id: '/(auth)/confirmRegister',
  path: '/confirmRegister',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutRouteRoute = appLayoutRouteRouteImport.update({
  id: '/(app)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutZoneRoute = appLayoutZoneRouteImport.update({
  id: '/zone',
  path: '/zone',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const appLayoutProfileRoute = appLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const appLayoutPredictionsRoute = appLayoutPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const appLayoutNotificationsRoute = appLayoutNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const appLayoutDashboardRoute = appLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const appLayoutCarteRoute = appLayoutCarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const appLayoutAlertsRoute = appLayoutAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => appLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/confirmRegister': typeof authConfirmRegisterRoute
  '/confirmSignIn': typeof authConfirmSignInRoute
  '/signIn': typeof authSignInRoute
  '/signUp': typeof authSignUpRoute
  '/verifyEmail': typeof authVerifyEmailRoute
  '/alerts': typeof appLayoutAlertsRoute
  '/carte': typeof appLayoutCarteRoute
  '/dashboard': typeof appLayoutDashboardRoute
  '/notifications': typeof appLayoutNotificationsRoute
  '/predictions': typeof appLayoutPredictionsRoute
  '/profile': typeof appLayoutProfileRoute
  '/zone': typeof appLayoutZoneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/confirmRegister': typeof authConfirmRegisterRoute
  '/confirmSignIn': typeof authConfirmSignInRoute
  '/signIn': typeof authSignInRoute
  '/signUp': typeof authSignUpRoute
  '/verifyEmail': typeof authVerifyEmailRoute
  '/alerts': typeof appLayoutAlertsRoute
  '/carte': typeof appLayoutCarteRoute
  '/dashboard': typeof appLayoutDashboardRoute
  '/notifications': typeof appLayoutNotificationsRoute
  '/predictions': typeof appLayoutPredictionsRoute
  '/profile': typeof appLayoutProfileRoute
  '/zone': typeof appLayoutZoneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/(app)/_layout': typeof appLayoutRouteRouteWithChildren
  '/(auth)/confirmRegister': typeof authConfirmRegisterRoute
  '/(auth)/confirmSignIn': typeof authConfirmSignInRoute
  '/(auth)/signIn': typeof authSignInRoute
  '/(auth)/signUp': typeof authSignUpRoute
  '/(auth)/verifyEmail': typeof authVerifyEmailRoute
  '/(app)/_layout/alerts': typeof appLayoutAlertsRoute
  '/(app)/_layout/carte': typeof appLayoutCarteRoute
  '/(app)/_layout/dashboard': typeof appLayoutDashboardRoute
  '/(app)/_layout/notifications': typeof appLayoutNotificationsRoute
  '/(app)/_layout/predictions': typeof appLayoutPredictionsRoute
  '/(app)/_layout/profile': typeof appLayoutProfileRoute
  '/(app)/_layout/zone': typeof appLayoutZoneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/confirmRegister'
    | '/confirmSignIn'
    | '/signIn'
    | '/signUp'
    | '/verifyEmail'
    | '/alerts'
    | '/carte'
    | '/dashboard'
    | '/notifications'
    | '/predictions'
    | '/profile'
    | '/zone'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/confirmRegister'
    | '/confirmSignIn'
    | '/signIn'
    | '/signUp'
    | '/verifyEmail'
    | '/alerts'
    | '/carte'
    | '/dashboard'
    | '/notifications'
    | '/predictions'
    | '/profile'
    | '/zone'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/(app)/_layout'
    | '/(auth)/confirmRegister'
    | '/(auth)/confirmSignIn'
    | '/(auth)/signIn'
    | '/(auth)/signUp'
    | '/(auth)/verifyEmail'
    | '/(app)/_layout/alerts'
    | '/(app)/_layout/carte'
    | '/(app)/_layout/dashboard'
    | '/(app)/_layout/notifications'
    | '/(app)/_layout/predictions'
    | '/(app)/_layout/profile'
    | '/(app)/_layout/zone'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  appLayoutRouteRoute: typeof appLayoutRouteRouteWithChildren
  authConfirmRegisterRoute: typeof authConfirmRegisterRoute
  authConfirmSignInRoute: typeof authConfirmSignInRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verifyEmail': {
      id: '/(auth)/verifyEmail'
      path: '/verifyEmail'
      fullPath: '/verifyEmail'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signUp': {
      id: '/(auth)/signUp'
      path: '/signUp'
      fullPath: '/signUp'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signIn': {
      id: '/(auth)/signIn'
      path: '/signIn'
      fullPath: '/signIn'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/confirmSignIn': {
      id: '/(auth)/confirmSignIn'
      path: '/confirmSignIn'
      fullPath: '/confirmSignIn'
      preLoaderRoute: typeof authConfirmSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/confirmRegister': {
      id: '/(auth)/confirmRegister'
      path: '/confirmRegister'
      fullPath: '/confirmRegister'
      preLoaderRoute: typeof authConfirmRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout': {
      id: '/(app)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout/zone': {
      id: '/(app)/_layout/zone'
      path: '/zone'
      fullPath: '/zone'
      preLoaderRoute: typeof appLayoutZoneRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/profile': {
      id: '/(app)/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appLayoutProfileRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/predictions': {
      id: '/(app)/_layout/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof appLayoutPredictionsRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/notifications': {
      id: '/(app)/_layout/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof appLayoutNotificationsRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/dashboard': {
      id: '/(app)/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appLayoutDashboardRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/carte': {
      id: '/(app)/_layout/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof appLayoutCarteRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/alerts': {
      id: '/(app)/_layout/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof appLayoutAlertsRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
  }
}

interface appLayoutRouteRouteChildren {
  appLayoutAlertsRoute: typeof appLayoutAlertsRoute
  appLayoutCarteRoute: typeof appLayoutCarteRoute
  appLayoutDashboardRoute: typeof appLayoutDashboardRoute
  appLayoutNotificationsRoute: typeof appLayoutNotificationsRoute
  appLayoutPredictionsRoute: typeof appLayoutPredictionsRoute
  appLayoutProfileRoute: typeof appLayoutProfileRoute
  appLayoutZoneRoute: typeof appLayoutZoneRoute
}

const appLayoutRouteRouteChildren: appLayoutRouteRouteChildren = {
  appLayoutAlertsRoute: appLayoutAlertsRoute,
  appLayoutCarteRoute: appLayoutCarteRoute,
  appLayoutDashboardRoute: appLayoutDashboardRoute,
  appLayoutNotificationsRoute: appLayoutNotificationsRoute,
  appLayoutPredictionsRoute: appLayoutPredictionsRoute,
  appLayoutProfileRoute: appLayoutProfileRoute,
  appLayoutZoneRoute: appLayoutZoneRoute,
}

const appLayoutRouteRouteWithChildren = appLayoutRouteRoute._addFileChildren(
  appLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  appLayoutRouteRoute: appLayoutRouteRouteWithChildren,
  authConfirmRegisterRoute: authConfirmRegisterRoute,
  authConfirmSignInRoute: authConfirmSignInRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
